#!/usr/bin/env python3
"""
BIW Pokal API Importer
Importiert gescrapte Daten in das FastAPI Backend
"""

import requests
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Set
from datetime import datetime
import time

# Setup Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('biw_import.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)


class BIWImporter:
    """Import scraped BIW data to FastAPI backend"""
    
    def __init__(self, base_url: str = "http://localhost:8000", api_key: Optional[str] = None):
        self.base_url = base_url.rstrip('/')
        self.session = requests.Session()
        
        # Set API Key if provided (for n8n-style auth)
        if api_key:
            self.session.headers.update({'X-API-Key': api_key})
        
        # Local cache for teams (name -> id mapping)
        self.team_cache: Dict[str, int] = {}
        
        # Track group_name -> group_id mapping per season
        self.season_groups: Dict[int, Dict[str, int]] = {}
        
        self.stats = {
            'seasons_created': 0,
            'teams_created': 0,
            'matches_created': 0,
            'errors': []
        }
        
    def load_data(self, filepath: str) -> Dict:
        """Load scraped JSON data"""
        logger.info(f"Loading data from {filepath}")
        with open(filepath, 'r', encoding='utf-8') as f:
            return json.load(f)
    
    def get_unique_teams_from_season(self, season_data: Dict) -> Set[str]:
        """Extract all unique team names from a season's data"""
        teams = set()
        for group_data in season_data['groups']:
            for match in group_data['matches']:
                teams.add(match['home_team'])
                teams.add(match['away_team'])
        return teams
    
    def create_season(self, season_number: int, participant_count: int) -> Optional[int]:
        """Create a season (groups are auto-generated by backend)"""
        url = f"{self.base_url}/api/seasons"
        
        payload = {
            "name": f"Saison {season_number}",
            "participant_count": participant_count,
            "status": "archived" if season_number < 50 else "active"
        }
        
        try:
            response = self.session.post(url, json=payload, timeout=10)
            response.raise_for_status()
            season_data = response.json()
            season_id = season_data['id']
            
            logger.info(f"✓ Created Season {season_number} (ID: {season_id}, {participant_count} participants)")
            self.stats['seasons_created'] += 1
            return season_id
            
        except requests.RequestException as e:
            error = f"Failed to create Season {season_number}: {str(e)}"
            logger.error(error)
            self.stats['errors'].append(error)
            return None
    
    def get_season_groups(self, season_id: int) -> Dict[str, int]:
        """Get all groups for a season and map name -> id"""
        url = f"{self.base_url}/api/seasons/{season_id}/groups"
        
        try:
            response = self.session.get(url, timeout=10)
            response.raise_for_status()
            groups = response.json()
            
            # Build mapping: group_name -> group_id
            mapping = {g['name']: g['id'] for g in groups}
            
            logger.info(f"  ✓ Retrieved {len(mapping)} groups: {list(mapping.keys())}")
            return mapping
            
        except requests.RequestException as e:
            error = f"Failed to get groups for season {season_id}: {str(e)}"
            logger.error(error)
            self.stats['errors'].append(error)
            return {}
    
    def create_team_in_season(self, season_id: int, team_name: str, group_id: int) -> Optional[int]:
        """Create/assign team to season and group"""
        # Check local cache first
        if team_name in self.team_cache:
            team_id = self.team_cache[team_name]
            logger.debug(f"    Team '{team_name}' from cache (ID: {team_id})")
            
            # Still need to assign to season
            return self.assign_team_to_season(season_id, team_id, group_id)
        
        # Team not in cache, create via API
        url = f"{self.base_url}/api/seasons/{season_id}/teams"

        payload = {
            "name": team_name,
            "logo_url": None,
            "onlineliga_url": None,
            "group_id": group_id  # Explizite Gruppenzuweisung
        }
        
        try:
            response = self.session.post(url, json=payload, timeout=10)
            response.raise_for_status()
            result = response.json()
            team_id = result['id']  # API returns 'id', not 'team_id'
            
            # Add to cache
            self.team_cache[team_name] = team_id
            
            logger.info(f"    ✓ Created Team '{team_name}' (ID: {team_id})")
            self.stats['teams_created'] += 1
            return team_id
            
        except requests.RequestException as e:
            # Check if it's a duplicate error
            if "409" in str(e) or "already" in str(e).lower():
                logger.debug(f"    Team '{team_name}' already exists")
                # Try to extract team_id from error or fetch it
                # For now, continue - the match creation will handle it
                return None
            
            error = f"Failed to create Team '{team_name}': {str(e)}"
            logger.error(error)
            self.stats['errors'].append(error)
            return None
    
    def assign_team_to_season(self, season_id: int, team_id: int, group_id: int) -> int:
        """Assign existing team to season/group (returns team_id for chaining)"""
        url = f"{self.base_url}/api/seasons/{season_id}/teams"
        
        payload = {
            "team_id": team_id,
            "group_id": group_id
        }
        
        try:
            response = self.session.post(url, json=payload, timeout=10)
            response.raise_for_status()
            return team_id
            
        except requests.RequestException as e:
            # Already assigned is OK
            if "409" in str(e) or "already" in str(e).lower():
                logger.debug(f"    Team {team_id} already in season {season_id}")
                return team_id
            
            logger.warning(f"Failed to assign Team {team_id}: {str(e)}")
            return team_id  # Return anyway, might still work
    
    def ensure_teams_exist(self, season_id: int, group_id: int, team_names: Set[str]):
        """Ensure all teams exist and are assigned to the season/group"""
        for team_name in team_names:
            self.create_team_in_season(season_id, team_name, group_id)
            time.sleep(0.05)  # Small delay
    
    def create_match(self, group_id: int, match_data: Dict) -> bool:
        """Create a match (correct endpoint: POST /api/groups/{id}/matches)"""
        url = f"{self.base_url}/api/groups/{group_id}/matches"
        
        # Get team IDs from cache (must have been created already)
        home_team_id = self.team_cache.get(match_data['home_team'])
        away_team_id = self.team_cache.get(match_data['away_team'])
        
        if not home_team_id or not away_team_id:
            error = f"Teams not in cache: {match_data['home_team']} vs {match_data['away_team']}"
            logger.error(f"    {error}")
            self.stats['errors'].append(error)
            return False
        
        payload = {
            "home_team_id": home_team_id,
            "away_team_id": away_team_id,
            "home_goals": match_data['home_goals'],
            "away_goals": match_data['away_goals'],
            "status": match_data['status'],
            "matchday": match_data['matchday'],
            "ingame_week": match_data.get('matchday', 1)
        }
        
        try:
            response = self.session.post(url, json=payload, timeout=10)
            response.raise_for_status()
            self.stats['matches_created'] += 1
            return True
            
        except requests.RequestException as e:
            error = f"Failed to create match {match_data['home_team']} vs {match_data['away_team']}: {str(e)}"
            logger.error(f"    {error}")
            self.stats['errors'].append(error)
            return False
    
    def import_season(self, season_data: Dict) -> bool:
        """Import complete season with all groups and matches"""
        season_number = season_data['season']
        logger.info(f"========== IMPORTING SEASON {season_number} ==========")
        
        # Calculate total participant count from unique teams
        all_teams = self.get_unique_teams_from_season(season_data)
        participant_count = len(all_teams)
        
        logger.info(f"  Detected {participant_count} unique teams across {len(season_data['groups'])} groups")
        
        # Create season (groups are auto-generated by backend based on participant_count)
        season_id = self.create_season(season_number, participant_count)
        if not season_id:
            return False
        
        # Fetch generated groups and map names to IDs
        groups_mapping = self.get_season_groups(season_id)
        if not groups_mapping:
            logger.error(f"  Failed to retrieve groups for season {season_id}")
            return False
        
        # Store mapping for this season
        self.season_groups[season_id] = groups_mapping
        
        # Import each group's data
        for group_data in season_data['groups']:
            group_name = group_data['group']
            
            # Get group_id from mapping
            group_id = groups_mapping.get(group_name)
            if not group_id:
                logger.warning(f"  Group {group_name} not found in backend groups {list(groups_mapping.keys())}")
                continue
            
            logger.info(f"  Importing Group {group_name} (ID: {group_id})...")
            
            # Extract unique teams in this group
            group_teams = set()
            for match in group_data['matches']:
                group_teams.add(match['home_team'])
                group_teams.add(match['away_team'])
            
            # Create/assign all teams first
            logger.info(f"    Creating {len(group_teams)} teams...")
            self.ensure_teams_exist(season_id, group_id, group_teams)
            
            # Import matches
            matches = group_data['matches']
            logger.info(f"    Importing {len(matches)} matches...")
            
            success_count = 0
            for match in matches:
                if self.create_match(group_id, match):
                    success_count += 1
                time.sleep(0.1)  # Rate limiting
            
            logger.info(f"    ✓ Imported {success_count}/{len(matches)} matches")
        
        logger.info(f"✓ Season {season_number} import complete")
        return True
    
    def import_all(self, data: Dict, skip_existing: bool = True):
        """Import all data"""
        logger.info("=" * 60)
        logger.info("STARTING IMPORT TO API")
        logger.info(f"API Base URL: {self.base_url}")
        logger.info("=" * 60)
        
        # Test API connection
        try:
            response = self.session.get(f"{self.base_url}/api/seasons", timeout=5)
            response.raise_for_status()
            logger.info("✓ API connection successful")
        except Exception as e:
            logger.error(f"✗ Cannot connect to API: {str(e)}")
            return
        
        # Import each season
        for season_data in data['seasons']:
            try:
                self.import_season(season_data)
                time.sleep(1)  # Pause between seasons
                
            except Exception as e:
                error = f"Failed to import Season {season_data['season']}: {str(e)}"
                logger.error(error, exc_info=True)
                self.stats['errors'].append(error)
                
                # Ask if we should continue
                if not self.should_continue():
                    logger.warning("Import aborted by user")
                    break
    
    def should_continue(self) -> bool:
        """Ask user if import should continue after error"""
        # For automated use, always continue
        # For interactive use, you could add input() here
        return True
    
    def print_summary(self):
        """Print import summary"""
        logger.info("")
        logger.info("=" * 60)
        logger.info("IMPORT SUMMARY")
        logger.info("=" * 60)
        logger.info(f"Seasons created: {self.stats['seasons_created']}")
        logger.info(f"Teams created: {self.stats['teams_created']}")
        logger.info(f"Matches created: {self.stats['matches_created']}")
        logger.info(f"Errors: {len(self.stats['errors'])}")
        
        if self.stats['errors']:
            logger.warning("")
            logger.warning("ERRORS:")
            for error in self.stats['errors'][:10]:  # Show first 10
                logger.warning(f"  - {error}")
            if len(self.stats['errors']) > 10:
                logger.warning(f"  ... and {len(self.stats['errors']) - 10} more")
        
        logger.info("=" * 60)


def main():
    """Main execution"""
    import argparse
    
    parser = argparse.ArgumentParser(description='Import BIW data to API')
    parser.add_argument('data_file', help='Path to scraped JSON data file')
    parser.add_argument('--api-url', default='http://localhost:8000',
                       help='API base URL (default: http://localhost:8000)')
    parser.add_argument('--api-key', default=None,
                       help='API key for authentication (optional)')
    parser.add_argument('--skip-existing', action='store_true',
                       help='Skip seasons that already exist')
    
    args = parser.parse_args()
    
    # Verify file exists
    data_path = Path(args.data_file)
    if not data_path.exists():
        logger.error(f"Data file not found: {args.data_file}")
        return
    
    # Create importer and run
    importer = BIWImporter(base_url=args.api_url, api_key=args.api_key)
    
    try:
        data = importer.load_data(args.data_file)
        importer.import_all(data, skip_existing=args.skip_existing)
        importer.print_summary()
        
    except KeyboardInterrupt:
        logger.warning("Import interrupted by user")
        importer.print_summary()
    except Exception as e:
        logger.error(f"Fatal error: {str(e)}", exc_info=True)


if __name__ == "__main__":
    main()
